# -*- coding: utf-8 -*-
{
    'name': "MRP KANTU",
    'summary': """
        Adaptaciones del modulo Mrp para Ceramicas Kantu""",
    'author': "Ceramicas Kantu S.A.C.",
    'website': "http://www.ceramicaskantu.com",
    'category': 'Manufacturing',
    'depends': ['base', 'mrp', 'hr', 'hr_attendance', 'web_auto_refresh'],
    'data': [
        'security/kantu_mrp.xml',
        'security/ir.model.access.csv',
        'data/mrp_kantu_data.xml',
        'report/report_mrp_production.xml',
        'report/report_kantu_productivity.xml',
        'views/production_resume_report.xml',
        'views/mrp_kantu_assets.xml',
        'views/mrp_order_production.xml',
        'views/mrp_order_line.xml',
        'views/product_template.xml',
        'views/mrp_production.xml',
        'wizard/mrp_transferencia.xml',
        'views/mrp_merma.xml',
        'views/mrp_workorder.xml',
        'views/mrp_workcenter.xml',
        'views/mrp_pago.xml',
        'views/stock_picking_type.xml',
        'views/mrp_kantu_templates.xml',
        'views/mrp_bom.xml',
        'views/mrp_routing_workcenter.xml',
        'views/mrp_periodo.xml',
        'report/mrp_production_templates.xml',
        'wizard/import_op.xml',
        'views/mrp_group_pay.xml',
    ],
    'qweb': [
        "static/src/xml/mrp_production.xml",
    ],
}
